version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: financial-record-processing-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/financeDB

  python-script:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://app:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    build:
      context: ./python
    container_name: python-data-loader
    depends_on:
      - app